name: Docker package cleanup

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    # The (restricted) default permissions are only read access for contents,
    # but we need to write packages also. As all not explicitly stated
    # permissions are none, we need to add contents: read, too.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Delete old scheduled images
        uses: actions/delete-package-versions@v4
        with:
          package-name: linters
          package-type: container
          min-versions-to-keep: 4

      - name: Delete images from deleted branches
        run: |
          # Get all image tags, API access described at
          # https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#list-packages-for-a-user
          api_result="$(curl -sL -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/users/chprat/packages/container/linters/versions)"
          # Remove main, latest and all date tags from the list
          filtered_image_tags="$(echo "$api_result" | jq -r ".[].metadata.container.tags[]" \
                                  | grep -v "^[0-9]*$\|latest\|main" || true)"
          # Check if we need to run
          if [ -z "$filtered_image_tags" ]; then
              number_of_tags=0
          else
              number_of_tags="$(echo "$filtered_image_tags" | wc -l)"
          fi
          echo "$number_of_tags possible tags to delete"
          if [[ $number_of_tags -eq 0 ]]; then
              exit
          fi
          # iterate over the filtered list of image tags
          while IFS= read -r line ; do
            # check if a branch for the tag exists
            if ! git ls-remote --exit-code --heads origin "$line" &> /dev/null; then
              # get the ID of the tagged image
              image_id="$(echo "$api_result" | jq -r ".[] | select(.metadata.container.tags[] == \"$line\") | .id")"
              echo "$line branch doesn't exist anymore, delete the image"
              # delete the image, API access described at
              # https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#delete-package-version-for-a-user
              curl -sL -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/users/chprat/packages/container/linters/versions/$image_id"
            else
              echo "$line branch still exists"
            fi
          done <<< "$filtered_image_tags"

